### ISSUE TITLE
The score of dataset v2. 

### ISSUE THREAD

**Issue by attackon1point6** [guoyang9/AdaVQA#2]
Hello, I find that the method proposed in the paper performs well on the cp-v2 dataset but shows poor results on the **v2** dataset (with a score around **26** when **not modifying hyperparameters**). Should I consider adjusting hyperparameters specifically for these two datasets?What is the best score you achieved on the **v2** dataset?

**Comment by guoyang9** [comment]
I haven't done experiments on the original VQA v2 dataset since it is more biased.
But you can try to tune the entropy [value](https://github.com/guoyang9/AdaVQA/blob/eec47df9cfc44cdade488a684edc363ea5dfe4ed/utils/config.py#L9C5-L9C5) to see whether it affects the final model performance.

**Comment by attackon1point6** [comment]
Oh!Thank you for your reply!I'll try it.
